In [1]:
import pandas as pd
import numpy as np

In [101]:
data = pd.read_csv("champaign_pavement_cleaned.csv")

In [115]:
data[data["Branch Name"] == "STANAGE AVE"]

,Branch ID,Branch Name,Section ID,From,To,Rank,Surface,Bus Route?,Length,Width,...,Planning Zone,Curb Type,Curb Reveal,2015 Pct Load,2015 PCI (measured),2016 PCI,2017 PCI,2018 PCI,2019 PCI,2020 PCI
2336,STANGA,STANAGE AVE,W01,NEIL ST,RANDOLPH ST,R,APC,N,408,26,...,PZ05,B6.18,4.5 in,0,70,68,65,63,60,58
2337,STANGA,STANAGE AVE,W02,RANDOLPH ST,STATE ST,R,PCC,N,425,27,...,PZ05,B6.18,6.0 in,93,74,73,72,70,69,68
2338,STANGA,STANAGE AVE,W03,STATE ST,PRAIRIE ST,R,PCC,N,447,27,...,PZ05,B7.18,7.0 in,87,61,60,59,57,56,55
2339,STANGA,STANAGE AVE,W04,PRAIRIE ST,ELM ST,R,PCC,N,461,26,...,PZ05,B6.18,6.0 in,71,67,66,65,63,62,61
2340,STANGA,STANAGE AVE,W05,ELM ST,ELM BOULEVARD,R,AAC,N,146,26,...,PZ05,B6.18,3.0 in,0,100,97,94,90,87,83

In [135]:
# replace long names with abbr
column_replace = ["Branch Name", "From", "To"]
from_to = ["From", "To"]
replace_list = [("DRIVE", "DR"), 
                ("STREET", "ST"), 
                ("AVENUE", "AVE"), 
                ("LANE", "LN"), 
                ("STREET", "ST"),
                ("CIRCLE", "CIR"),
                ("PLACE", "PL"),
                ("SQUARE", "SQ"),
                ("COURT", "CT"),
                ("BOULEVARD", "BLVD"),
                ("ROAD", "RD")]
takeout_list = [("OF", "")]


for name in replace_list:
    data[col] = data[col].map(lambda a: a.replace(name[0], name[1]))
for takeout in takeout_list:
    data[col] = data[col].map(lambda a: a.replace(takeout[0], takeout[1]))

# for col in from_to:
#     for row in data.iterrows():
#         data_list = data[col].loc[row].split(".")
#         if len(data_list) == 2:
#             data[col].iloc[row] = data_list[1]
#         else:
#             data[col].iloc[row] = data_list[0]

In [136]:
data['UniqueID'] = data['Branch ID'] + ';' + data['Section ID']

In [150]:
data_no_dir = data
for col in from_to:
    for i in np.arange(len(data_no_dir)):
        data_list = data_no_dir[col].loc[i].split(".")
        if len(data_list) == 2:
            data_no_dir[col].iloc[row] = data_list[1]
#         else:
#             data_no_dir[col].iloc[row] = data_list[0]

In [148]:
data_no_dir['From'].loc[0].split(".")

['WYNDMERE POINT']

In [156]:
data_no_dir.to_csv('pavement_cleaned.csv')

In [158]:
clean = pd.read_csv('pavement_cleaned.csv')

In [159]:
clean.head()

,Unnamed: 0,Branch ID,Branch Name,Section ID,From,To,Rank,Surface,Bus Route?,Length,...,Curb Type,Curb Reveal,2015 Pct Load,2015 PCI (measured),2016 PCI,2017 PCI,2018 PCI,2019 PCI,2020 PCI,UniqueID
0,0,ABYFLD,ABBEY FIELDS DR,W46,WYNDMERE POINT,E. SIDE ENGLISH OAK CIR,R,PCC,N,847,...,B6.18,6.0 in,7,83,82,80,79,78,76,ABYFLD;W46
1,1,ABYFLD,ABBEY FIELDS DR,W48A,W. SIDE ENGLISH OAK CIR,117' W. ENGLISH OAK CIR,R,PCC,N,133,...,B6.18,6.0 in,47,89,88,86,85,84,82,ABYFLD;W48A
2,2,ABYFLD,ABBEY FIELDS DR,W48B,117' W. ENGLISH OAK CIR,JACOBS BLVD,R,PCC,N,135,...,B6.18,6.0 in,0,92,91,89,88,87,85,ABYFLD;W48B
3,3,ABYFLD,ABBEY FIELDS DR,W49,JACOBS BLVD,TREY BLVD/MARIE BLVD,R,PCC,N,983,...,B6.18,6.0 in,0,92,91,89,88,87,85,ABYFLD;W49
4,4,ABERDND,ABERDEEN DR,W39,COBBLEFIELD RD,PRESTWICK POINT,R,AC,N,766,...,M2.12,2.5 in,52,74,71,69,66,64,61,ABERDND;W39